require("eighchang.plugins-setup")
require("eighchang.core.options")
require("eighchang.core.keymaps")
require("eighchang.core.colorscheme")
require("eighchang.plugins.comment")
require("eighchang.plugins.lualine")
require("eighchang.plugins.nvim-tree")
require("eighchang.plugins.telescope")
